name: build-package
on:
  pull_request:
    types: [closed]

jobs:
  miyazaki-infra-staging-deployment:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout public repo
        uses: actions/checkout@master

      - name: Check the cntext
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Check the latest commit ID
        run: echo "$GITHUB_CONTEXT"
        env:
          BRANCH_TAG: ${{ toJson(github.event.pull_request.head.sha) }}

      - name: Check the merge commit ID
        run: echo "$GITHUB_CONTEXT"
        env:
          MASTER_TAG: ${{ toJson(github.event.pull_request.merge_commit_sha) }}

      - name: dockerize the branch tag
        run: export BRANCH_TAG=`printf $BRANCH_COMMMIT_ID | cut -c1-7` && docker build -t docker.pkg.github.com/syukur91/my-mono/hello-world:$BRANCH_TAG  .
        working-directory: src
        env:
          BRANCH_COMMMIT_ID: ${{ toJson(github.event.pull_request.head.sha) }}

      - name: retag
        run: export MASTER_TAG=`printf $MASTER_COMMIT_ID  | cut -c1-7` && docker tag docker.pkg.github.com/syukur91/my-mono/hello-world:$BRANCH_TAG docker.pkg.github.com/syukur91/my-mono/hello-world:$MASTER_TAG 
        working-directory: src
        env:
          MASTER_COMMIT_ID: ${{ toJson(github.event.pull_request.merge_commit_sha) }}
      
      # - name: push the docker
      #   run: docker push docker.pkg.github.com/syukur91/my-mono/hello-world:$BRANCH_TAG  .
      #   working-directory: src
      #   env:
      #     BRANCH_COMMMIT_ID: ${{ toJson(github.event.pull_request.head.sha) }}

          
