name: tag-ref
on: 
 push:
    tags:
      - test-code-prod-*

jobs:
  miyazaki-infra-staging-deployment:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout public repo
        uses: actions/checkout@master

      - name: Check the cntext
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: login to our private repository
        run: docker login docker.pkg.github.com --username techacc -p $TOKEN 2>/dev/null
        env:
          TOKEN: ${{ secrets.PERSONAL_DEV_TOKEN }}

     

          
